apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: nginxpod
      image: nginx:alpine
      ports:
        - containerPort: 80
